sdm660-common: Patch libqxrsplitauxservice.qti to fix duplicate versions
error: vendor/xiaomi/sdm660-common/Android.bp:7436:1: module "libqxrsplitauxservice.qti" variant "android_arm64_armv8-a_cortex-a73_static":
depends on multiple versions of the same aidl_interface: android.media.audio.common.types-V3-cpp-source, android.media.audio.common.types-V4-cpp-source

Signed-off-by: ImSpiDy <SpiDy2713@gmail.com>